.TH NHC98ARCH 1 local
.SH NAME
nhc98arch \- determine machine architecture for nhc98
.SH SYNOPSIS
.B nhc98arch
.SH DESCRIPTION
.I nhc98arch is a simple script to determine a canonical name for
your machine architecture in a format that the
.I nhc98
compiler will recognise.

.SH FILES
.TP 25
.B /usr/local/bin/nhc98arch

.SH "SEE ALSO"
hmake(1), nhc98(1)
