include Makefile.inc

THISLIB	= Random
SEARCH	=

SRCS	=
SRCS_T	=

ifeq "${BUILDWITH}" "hbc"
EXTRA_H_FLAGS   =       +RTS -H16M -A2M -RTS
endif

# Here are the main rules.
include ../Makefile.common


# Here are the dependencies.
