module Char
    (module IsAlpha
    ,module IsAlphanum
    ,module IsAscii
    ,module IsControl
    ,module IsDigit
    ,module IsHexDigit
    ,module IsLower
    ,module IsOctDigit
    ,module IsPrint
    ,module IsSpace
    ,module IsUpper
    ,module ToLower
    ,module ToUpper
    ) where

import IsAlpha
import IsAlphanum
import IsAscii
import IsControl
import IsDigit
import IsHexDigit
import IsLower
import IsOctDigit
import IsPrint
import IsSpace
import IsUpper
import ToLower
import ToUpper
