include Makefile.inc

THISLIB	= DErrNo
SEARCH	=
EXTRA_C_FLAGS	=
ifeq "${BUILDWITH}" "ghc"
EXTRA_H_FLAGS	=	+RTS -K2M -RTS
endif
ifeq "${BUILDWITH}" "hbc"
EXTRA_H_FLAGS	=	+RTS -H32M -A2M -RTS
endif
ifeq "${BUILDWITH}" "gcc"
EXTRA_H_FLAGS	=	+RTS -H32M -RTS
endif
ifeq "${BUILDWITH}" "nhc98"
EXTRA_H_FLAGS	=	+RTS -H32M -RTS
endif


SRCS	=
SRCS_T	=


# Here are the main rules.
include ../Makefile.common


# Here are the dependencies.
