#!/bin/sh -e

NHC98LIBDIR=${NHC98LIBDIR-.}

CLASSPATH=$NHC98LIBDIR/hat-trail.jar
export CLASSPATH
PATH=${JAVADIR}/bin:$PATH
export PATH
echo hat-trail: starting java browser ...
java nhctracer.HatTrail $* &
