#!/bin/sh -e
# Starts up the tracer user-interface

NHC98LIBDIR=${NHC98LIBDIR-.}

CLASSPATH=$NHC98LIBDIR/rtb.jar
export CLASSPATH
PATH=${JAVADIR}/bin:$PATH
export PATH
echo Redex Trail Browser started, please wait for java to initialise...
java -Dtracer.tracefont=Helvetica:14 -Dtracer.outputfont=Courier:14 -Dtracer.sourcefont=Courier:14 nhctracer.NhcTracer 6710 $* &
