#!/bin/sh
#	fixghc:  a small script to patch up the -syslib changes between
#		versions 4.04 and 4.06 of ghc.

ghcversion=$1
shift

if [ $ghcversion -ge 406 ]
then
  while test "'$1'" != "''" 
  do
    case $1 in
      -syslib) shift
               case $1 in
                 exts) echo -n " -syslib lang";;
                 misc) ;;
                 *)    echo -n " -syslib $1" ;;
               esac ;;
      *) echo -n " $1" ;;
    esac
    shift
  done
  echo
else
  echo "$@"
fi
