#!/bin/sh
#	simple redirection script to find the correct executable
#	for this machine architecture
NHC98LIBDIR=${NHC98LIBDIR-/usr/home/sparud/tracer/nhc98-1.0pre9/lib}
MACHINE=${MACHINE-"`/usr/home/sparud/tracer/nhc98-1.0pre9/script/harch`"}
exec $NHC98LIBDIR/$MACHINE/`basename $0` $@
