#!/bin/sh
#       harch - determine canonical processor architecture
#		Nov 1998: first used.
#		May 1999: ensure that small differences (e.g. kernel version)
#			  don't matter.

PROCESSOR=
OS=
REL=

#  Unfortunately, there are a variety of incompatible
#  ways of detecting architecture, so try them all!

if which uname >/dev/null 2>&1
then
  if uname -p >/dev/null 2>&1
  then PROCESSOR=`uname -p`
       if [ "$PROCESSOR" = "unknown" ]
       then PROCESSOR=`uname -m`
       fi
  else
    if which arch >/dev/null 2>&1
    then PROCESSOR=`arch`
    else PROCESSOR=`uname -m`
    fi
  fi
  OS=`uname -s`
  REL=`uname -r`
else
  if which arch >/dev/null 2>&1
  then PROCESSOR=`arch`
  else
    if which machine >/dev/null 2>&1
    then PROCESSOR=`machine`
    else PROCESSOR='unknown'
    fi
  fi
  OS=unknown
fi


# Canonicalise equivalent processor families to one representative member.
case $PROCESSOR in
  i[345678]86)	PROCESSOR=ix86;;
  sun3*)	PROCESSOR=sun3;;
  sun4*)	PROCESSOR=sun4;;
  sparc*)	PROCESSOR=sparc;;
esac

# Keep OS release number only if it might be relevant.
case $OS in
  unknown)	;;
  Linux)	;;
  *BSD)		;;
  BSD/OS)	OS="BSD-OS"$REL ;;
  SunOS)	case $REL in
		  3*) OS=SunOS3;;
		  4*) OS=SunOS4;;
		  5*) OS=solaris2;;
		  6*) OS=solaris3;;
		  7*) OS=solaris7;;
		  *)  OS=SunOS-$REL;;
		esac;;
  IRIX*)	case $REL in
		  5*) OS=IRIX5;;
		  6*) OS=IRIX6;;
		  *)  OS=IRIX-$REL;;
		esac;;
  *)		OS=$OS-$REL;;
esac

# And that's it.
echo $PROCESSOR-$OS
