#!/bin/sh
case $1 in
  base)
	echo Data Debug Control Control/Monad System System/IO System/Console
	echo Text Text/PrettyPrint Text/Html Text/Show Text/ParserCombinators
	echo Text/Regex Foreign Foreign/Marshal Foreign/C NHC
	;;
  Cabal)
	echo Distribution Distribution/Compat Distribution/PreProcess
	echo Distribution/Simple
	;;
  fgl)
	echo Data Data/Graph Data/Graph/Inductive Data/Graph/Inductive/Monad
	echo Data/Graph/Inductive/Query Data/Graph/Inductive/Internal
	;;
  GLUT)
	echo Graphics Graphics/UI Graphics/UI/GLUT Graphics/UI/GLUT/Callbacks
	;;
  HaXml)
	echo Text Text/ParserCombinators Text/XML Text/XML/HaXml
	echo Text/XML/HaXml/Html Text/XML/HaXml/Xtract
	;;
  HUnit)
	echo Test Test/HUnit
	;;
  haskell-src)
	echo Language Language/Haskell
	;;
  Japi) echo Graphics Graphics/UI Graphics/UI/Japi
	;;
  monads)
	echo Monad
	echo Unstable Unstable/Control Unstable/Control/Monad
	echo Unstable/Control/Monad/Private Unstable/Control/Monad/ST
	;;
  mtl)	echo Control Control/Monad
	;;
  network)
	echo Network
	;;
  OpenGL)
	echo Graphics Graphics/Rendering Graphics/Rendering/OpenGL
	echo Graphics/Rendering/OpenGL/GL
	echo Graphics/Rendering/OpenGL/GL/PixelRectangles
	echo Graphics/Rendering/OpenGL/GL/Texturing
	echo Graphics/Rendering/OpenGL/GLU
	;;
  parsec)
	echo Text Text/ParserCombinators Text/ParserCombinators/Parsec
	;;
  QuickCheck)
	echo Test Test/QuickCheck Debug Debug/QuickCheck
	;;
  readline)
	echo System System/Console
	;;
  *)
	;;
esac
