#!/bin/sh
case $1 in
  base)	echo Data Debug Control Control/Monad System System/IO System/Console
	echo Text Text/ParserCombinators Text/ParserCombinators/Parsec
	echo Text/PrettyPrint Foreign Foreign/Marshal Foreign/C
	;;
  *) ;;
esac
