module Binary
(Var "<<",Has{args=2,fixity=L,priority=9,letBound=True})
(Var "alignBin",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "binPtr2Int",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "clearBits",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "closeBin",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "compareBin",Has{args=6,fixity=Def,priority=9,letBound=True})
(Var "copyBin",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "copyBits",Has{args=5,fixity=Def,priority=9,letBound=True})
(Var "copyBytes",Has{args=3,fixity=Def,priority=9,letBound=True})
(Var "endBin",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "equalsBin",Has{args=5,fixity=Def,priority=9,letBound=True})
(Var "freezeBin",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "getAt",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "getBits",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "getBitsF",Has{args=3,fixity=Def,priority=9,letBound=True})
(Var "getFAt",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "incBinPtr",Has{args=0,fixity=Def,priority=9,letBound=True})
(Var "int2BinPtr",Has{args=0,fixity=Def,priority=9,letBound=True})
(Var "isEOFBin",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "openBin",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "putAt",Has{args=3,fixity=Def,priority=9,letBound=True})
(Var "putAtEnd",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "putBits",Has{args=3,fixity=Def,priority=9,letBound=True})
(Var "seekBin",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "sizeofBinPtr",Has{args=0,fixity=Def,priority=9,letBound=True})
(Var "skipBits",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "stdmem",Has{args=0,fixity=Def,priority=9,letBound=True})
(Var "tellBin",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "unsafeShiftBinPtr",Has{args=2,fixity=Def,priority=9,letBound=True})
(Con "BinIOMode" "RO",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "BinIOMode" "RW",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "BinIOMode" "WO",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "BinLocation" "File",Has{args=2,fixity=Def,priority=9,letBound=True})
(Con "BinLocation" "Memory",Has{args=0,fixity=Def,priority=9,letBound=True})
(Method "Binary" "get",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Binary" "getF",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Binary" "put",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Binary" "sizeOf",Has{args=(-1),fixity=Def,priority=9,letBound=True})
