module Bit
(Method "Bits" "^&",Has{args=(-1),fixity=L,priority=7,letBound=True})
(Method "Bits" "^<<",Has{args=(-1),fixity=L,priority=8,letBound=True})
(Method "Bits" "^>>",Has{args=(-1),fixity=L,priority=8,letBound=True})
(Method "Bits" "^|",Has{args=(-1),fixity=L,priority=6,letBound=True})
(Method "Bits" "asr",Has{args=(-1),fixity=L,priority=8,letBound=True})
(Method "Bits" "bitSize",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Bits" "clear",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Bits" "compl",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Bits" "rol",Has{args=(-1),fixity=L,priority=8,letBound=True})
(Method "Bits" "ror",Has{args=(-1),fixity=L,priority=8,letBound=True})
(Method "Bits" "set",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Bits" "test",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Bits" "xor",Has{args=(-1),fixity=L,priority=5,letBound=True})
