module Complex
(Var "cis",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "conjugate",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "imagPart",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "magnitude",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "mkPolar",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "phase",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "polar",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "realPart",Has{args=1,fixity=Def,priority=9,letBound=True})
(Con "Complex" ":+",Has{args=2,fixity=None,priority=6,letBound=True})
