module Directory
(Var "createDirectory",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "doesDirectoryExist",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "doesFileExist",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "getCurrentDirectory",Has{args=0,fixity=Def,priority=9,letBound=True})
(Var "getDirectoryContents",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "getModificationTime",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "getPermissions",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "removeDirectory",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "removeFile",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "renameDirectory",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "renameFile",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "setCurrentDirectory",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "setPermissions",Has{args=2,fixity=Def,priority=9,letBound=True})
(Con "Permissions" "Permissions",Has{args=4,fixity=Def,priority=9,letBound=True})
