module FFI
(Var "addrToStablePtr",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "deRefStablePtr",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "foreignObjToAddr",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "free",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "freeForeignObj",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "freeStablePtr",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "fromCString",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "getErrNo",Has{args=0,fixity=Def,priority=9,letBound=True})
(Var "makeForeignObj",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "makeStablePtr",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "malloc",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "mallocElem",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "mallocElems",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "mkIOError",Has{args=4,fixity=Def,priority=9,letBound=True})
(Var "nullAddr",Has{args=0,fixity=Def,priority=9,letBound=True})
(Var "plusAddr",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "realloc",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "stablePtrToAddr",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "throwIOError",Has{args=4,fixity=Def,priority=9,letBound=True})
(Var "toCString",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "touchForeignObj",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "withForeignObj",Has{args=2,fixity=Def,priority=9,letBound=True})
(Method "Storable" "alignment",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Storable" "peek",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Storable" "peekByteOff",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Storable" "peekElemOff",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Storable" "poke",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Storable" "pokeByteOff",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Storable" "pokeElemOff",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Storable" "sizeOf",Has{args=(-1),fixity=Def,priority=9,letBound=True})
