module IO
(Var "bracket",Has{args=3,fixity=Def,priority=9,letBound=True})
(Var "bracket_",Has{args=3,fixity=Def,priority=9,letBound=True})
(Var "hClose",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "hFileSize",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "hFlush",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "hGetBuffering",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "hGetChar",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "hGetContents",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "hGetLine",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "hGetPosn",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "hIsClosed",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "hIsEOF",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "hIsOpen",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "hIsReadable",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "hIsSeekable",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "hIsWritable",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "hLookAhead",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "hPrint",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "hPutChar",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "hPutStr",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "hPutStrLn",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "hReady",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "hSeek",Has{args=3,fixity=Def,priority=9,letBound=True})
(Var "hSetBuffering",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "hSetPosn",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "hWaitForInput",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "ioeGetErrorString",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "ioeGetFileName",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "ioeGetHandle",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "isAlreadyExistsError",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "isAlreadyInUseError",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "isDoesNotExistError",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "isEOF",Has{args=0,fixity=Def,priority=9,letBound=True})
(Var "isEOFError",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "isFullError",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "isIllegalOperation",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "isPermissionError",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "isUserError",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "openFile",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "openSocket",Has{args=3,fixity=Def,priority=9,letBound=True})
(Var "stderr",Has{args=0,fixity=Def,priority=9,letBound=True})
(Var "stdin",Has{args=0,fixity=Def,priority=9,letBound=True})
(Var "stdout",Has{args=0,fixity=Def,priority=9,letBound=True})
(Var "try",Has{args=1,fixity=Def,priority=9,letBound=True})
(Con "BufferMode" "BlockBuffering",Has{args=1,fixity=Def,priority=9,letBound=True})
(Con "BufferMode" "LineBuffering",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "BufferMode" "NoBuffering",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "IOMode" "AppendMode",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "IOMode" "ReadMode",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "IOMode" "ReadWriteMode",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "IOMode" "WriteMode",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "SeekMode" "AbsoluteSeek",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "SeekMode" "RelativeSeek",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "SeekMode" "SeekFromEnd",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "SocketType" "SocketDatagram",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "SocketType" "SocketRaw",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "SocketType" "SocketStream",Has{args=0,fixity=Def,priority=9,letBound=True})
