module Random
(Var "getStdGen",Has{args=0,fixity=Def,priority=9,letBound=True})
(Var "getStdRandom",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "mkStdGen",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "newStdGen",Has{args=0,fixity=Def,priority=9,letBound=True})
(Var "setStdGen",Has{args=1,fixity=Def,priority=9,letBound=True})
(Method "Random" "random",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Random" "randomIO",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Random" "randomR",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Random" "randomRIO",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Random" "randomRs",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "Random" "randoms",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "RandomGen" "genRange",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "RandomGen" "next",Has{args=(-1),fixity=Def,priority=9,letBound=True})
(Method "RandomGen" "split",Has{args=(-1),fixity=Def,priority=9,letBound=True})
