module Time
(Var "addToClockTime",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "calendarTimeToString",Has{args=0,fixity=Def,priority=9,letBound=True})
(Var "diffClockTimes",Has{args=2,fixity=Def,priority=9,letBound=True})
(Var "formatCalendarTime",Has{args=3,fixity=Def,priority=9,letBound=True})
(Var "getClockTime",Has{args=0,fixity=Def,priority=9,letBound=True})
(Var "hs_toCalendarTime",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "hs_toClockTime",Has{args=12,fixity=Def,priority=9,letBound=True})
(Var "hs_toUTCTime",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "toCalendarTime",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "toClockTime",Has{args=1,fixity=Def,priority=9,letBound=True})
(Var "toUTCTime",Has{args=1,fixity=Def,priority=9,letBound=True})
(Con "CalendarTime" "CalendarTime",Has{args=12,fixity=Def,priority=9,letBound=True})
(Con "ClockTime" "CT",Has{args=1,fixity=Def,priority=9,letBound=True})
(Con "Day" "Friday",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "Day" "Monday",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "Day" "Saturday",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "Day" "Sunday",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "Day" "Thursday",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "Day" "Tuesday",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "Day" "Wednesday",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "Month" "April",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "Month" "August",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "Month" "December",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "Month" "February",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "Month" "January",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "Month" "July",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "Month" "June",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "Month" "March",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "Month" "May",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "Month" "November",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "Month" "October",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "Month" "September",Has{args=0,fixity=Def,priority=9,letBound=True})
(Con "TimeDiff" "TimeDiff",Has{args=7,fixity=Def,priority=9,letBound=True})
